### ISSUE TITLE
getBroadcast() could be null in android on some interfaces

### ISSUE THREAD

**Issue by xmeow** [pusherman/react-native-network-info#59]
```
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.InetAddress.toString()' on a null object reference
        at com.pusherman.networkinfo.RNNetworkInfo.getBroadcast(RNNetworkInfo.java:63)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:163)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:760)
```
A possible fix would be add some check to broadcast address

```
    @ReactMethod
    public void getBroadcast(/*@NonNull String ip, */final Callback callback) {
        String ipAddress = null;

        for (InterfaceAddress address : getInetAddresses()) {
            if (!address.getAddress().isLoopbackAddress()/*address.getAddress().toString().equalsIgnoreCase(ip)*/) {
                InetAddress broadCast = address.getBroadcast();
                if (broadCast != null){
                    ipAddress = broadCast.toString();
                }
            }
        }

        callback.invoke(ipAddress);
    }
```

**Comment by GabrielDuarteJr** [comment]
+1

**Comment by fotonmoton** [comment]
Any news on this issue?
Get this error on Xiaomi Note 4X with Android 7:
![screenshot_2018-12-17-14-11-50-618_com mrcat_waiter](https://user-images.githubusercontent.com/7763084/50086772-ba4a4680-0206-11e9-9267-7de5c5a6cb67.png)

**Comment by Sanjeet1** [comment]
> Any news on this issue?
> Get this error on Xiaomi Note 4X with Android 7:
> ![screenshot_2018-12-17-14-11-50-618_com mrcat_waiter](https://user-images.githubusercontent.com/7763084/50086772-ba4a4680-0206-11e9-9267-7de5c5a6cb67.png)

me too

**Comment by hevili** [comment]
me too on huawei p10

**Comment by JerryLinyong** [comment]
me too!!

**Comment by shynst** [comment]
+1
please fix!

**Comment by pjunior94** [comment]
same error here, fix it guys pls.
